# default profile:
default: --profile qa --publish-quiet


# env profiles
local: ENVIRONMENT=local ENDPOINT=http://localhost:5000/ BROWSER=chrome_remote
qa: ENVIRONMENT=qa ENDPOINT=https://simple-book-store-app-qa.herokuapp.com/ BROWSER=chrome_remote
prod: ENVIRONMENT=prod ENDPOINT=https://simple-book-store-app.herokuapp.com/ BROWSER=chrome_remote