source 'https://rubygems.org/'

gem 'activesupport'
gem 'cucumber'
gem 'page-object'
gem 'watir'
gem 'require_all'
gem 'faker'
gem 'ffi'
gem 'rspec'
gem 'rake'

gem 'rexml'

group :debug, optional: true do
  gem 'debase'
end