require 'cucumber/rake/task'

task :run_test do |task, args|
  puts "rake task: #{task}"
  ENV['ENVIRONMENT'] = 'local'
  ENV['BROWSER'] = 'edge'
  cucumber_test_tags = "@test_case_1"
  Cucumber::Rake::Task.new(:run_test) { |cucumber_task|
    cucumber_task.cucumber_opts = %Q{ --format pretty --tags '#{cucumber_test_tags}' --profile #{ENV['ENVIRONMENT']}}
  }
end